services:
  postgres:
    image: postgres:16
    container_name: imo_postgres
    environment:
      POSTGRES_DB: imo
      POSTGRES_USER: imo
      POSTGRES_PASSWORD: imo
    ports:
      - "5432:5432"
    volumes:
      - imo_pg_data:/var/lib/postgresql/data

volumes:
  imo_pg_data:

