server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/imo}
    username: ${SPRING_DATASOURCE_USERNAME:imo}
    password: ${SPRING_DATASOURCE_PASSWORD:imo}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

#camunda:
#  bpm:
#    metrics:
#      enabled: false
#      db-reporter-activate: false
#    history-level: ACTIVITY
#    admin-user:
#      id: demo
#      password: demo
#      firstName: Demo
#    filter:
#      create: All tasks

imo:
  recipes:
    catalogResource: classpath:recipes/catalog.json
